name: 'GH Build Matrix'
description: 'Outputs list of containers for other actions to use'
inputs:
  n:
    description: 'Number of parallel containers'
    required: true
    default: 1
outputs:
  matrix:
    description: 'Matrix strategy JSON string'
runs:
  using: 'composite'
  steps:
    - name: Build matrix
      shell: bash
      run: echo "matrix=$(${{ github.action_path }}/entrypoint.sh ${{ inputs.n }})" >> $GITHUB_OUTPUT
